CREATE DATABASE feedback;

USE feedback;

CREATE TABLE feedbacks (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    texto TEXT NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);